name: pt_1_20_1
version: '1.0.0'
main: PT.Main
api-version: '1.20'
authors: [ 挽枫 ]
description: PT服务器在1.20.1的专用插件(注，还需服务端)
commands:
  login:
    description: 登录到服务器(需要在服务端生效时使用，请在服务端注册!)
  l:
    description: “login”命令的缩写，登录到服务器(需要在服务端生效时使用，请在服务端注册!)
  get_player_head:
    description: “获取指定玩家的头颅”